import { TalkRecord } from './types';

const createHistory = (dateTime: string, foremanName: string) => [{
    timestamp: dateTime,
    action: 'CREATED' as const,
    details: 'Talk record submitted by foreman.',
    actor: foremanName,
}];

export const MOCK_TALK_RECORDS: TalkRecord[] = [
  {
    id: 'talk-001',
    dateTime: '2025-10-08T07:05:12Z',
    location: '123 Main St, Site A',
    topic: 'Fall Protection',
    topicId: 'topic-005',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'Frank Miller',
    crewSignatures: [
      { name: 'John Doe', signature: null },
      { name: 'Jane Smith', signature: null },
      { name: 'Mike Ross', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-08T07:05:12Z', 'Frank Miller'),
  },
  {
    id: 'talk-002',
    dateTime: '2025-10-07T07:10:30Z',
    location: '456 Oak Ave, Site B',
    topic: 'Personal Protective Equipment (PPE)',
    topicId: 'topic-010',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'Sarah Chen',
    crewSignatures: [
      { name: 'Carlos Ray', signature: null },
      { name: 'Emily White', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-07T07:10:30Z', 'Sarah Chen'),
  },
  {
    id: 'talk-003',
    dateTime: '2025-10-06T07:02:45Z',
    location: '123 Main St, Site A',
    topic: 'Hazard Communication',
    topicId: 'topic-007',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'Frank Miller',
    crewSignatures: [
      { name: 'John Doe', signature: null },
      { name: 'Jane Smith', signature: null },
      { name: 'Mike Ross', signature: null },
      { name: 'Lisa Ray', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-06T07:02:45Z', 'Frank Miller'),
  },
  {
    id: 'talk-004',
    dateTime: '2025-10-05T07:15:00Z',
    location: '789 Pine Ln, Site C',
    topic: 'Electrical Safety',
    topicId: 'topic-003',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'David Kim',
    crewSignatures: [
      { name: 'Peter Jones', signature: null },
      { name: 'Anna Garcia', signature: null },
      { name: 'Tom Wilson', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-05T07:15:00Z', 'David Kim'),
  },
    {
    id: 'talk-005',
    dateTime: '2025-10-04T07:08:22Z',
    location: '456 Oak Ave, Site B',
    topic: 'Scaffolding Safety',
    topicId: 'topic-011',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'Sarah Chen',
    crewSignatures: [
      { name: 'Carlos Ray', signature: null },
      { name: 'Emily White', signature: null },
      { name: 'Steve Holt', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-04T07:08:22Z', 'Sarah Chen'),
  },
  {
    id: 'talk-006',
    dateTime: '2025-10-03T07:01:50Z',
    location: '123 Main St, Site A',
    topic: 'Trenching and Excavation',
    topicId: 'topic-012',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'Frank Miller',
    crewSignatures: [
      { name: 'John Doe', signature: null },
      { name: 'Jane Smith', signature: null },
      { name: 'Mike Ross', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-03T07:01:50Z', 'Frank Miller'),
  },
  {
    id: 'talk-007',
    dateTime: '2025-10-02T07:11:11Z',
    location: '789 Pine Ln, Site C',
    topic: 'Fire Prevention',
    topicId: 'topic-006',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'David Kim',
    crewSignatures: [
      { name: 'Peter Jones', signature: null },
      { name: 'Anna Garcia', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-02T07:11:11Z', 'David Kim'),
  },
  {
    id: 'talk-008',
    dateTime: '2025-10-01T07:03:18Z',
    location: '456 Oak Ave, Site B',
    topic: 'Tool and Equipment Safety',
    topicId: 'topic-002',
    topicPdfUrl: '/mock-topic.pdf',
    foremanName: 'Sarah Chen',
    crewSignatures: [
      { name: 'Carlos Ray', signature: null },
      { name: 'Emily White', signature: null },
      { name: 'Steve Holt', signature: null },
    ],
    syncStatus: 'synced',
    recordStatus: 'submitted',
    history: createHistory('2025-10-01T07:03:18Z', 'Sarah Chen'),
  },
];